CREATE DATABASE 1907002160_lokaverkefni;
USE 1907002160_lokaverkefni;

#1
CREATE TABLE MEMBERSHIP (
MEM_NUM INT PRIMARY KEY NOT NULL,
MEM_FNAME VARCHAR(32) NOT NULL,
MEM_LNAME VARCHAR(32) NOT NULL,
MEM_STREET VARCHAR(32) NOT NULL,
MEM_CITY VARCHAR(32) NOT NULL,
MEM_STATE CHAR(2) NOT NULL,
MEM_ZIP CHAR(5)NOT NULL,
MEM_BALANCE DECIMAL(5,2)
);

CREATE TABLE RENTAL (
RENT_NUM INT PRIMARY KEY NOT NULL,
RENT_DATE DATE,
MEM_NUM INT NOT NULL,
FOREIGN KEY (MEM_NUM) REFERENCES MEMBERSHIP(MEM_NUM)
);

CREATE TABLE PRICE (
PRICE_CODE VARCHAR(1) NOT NULL PRIMARY KEY,
PRICE_DESCRIPTION VARCHAR(100),
PRICE_RENTFEE INT NOT NULL,
PRICE_DAILYLATEFEE INT
);

CREATE TABLE MOVIE (
MOVIE_NUM INT NOT NULL PRIMARY KEY,
MOVIE_TITLE VARCHAR(255) NOT NULL,
MOVIE_YEAR YEAR,
MOVIE_COST DECIMAL(3,2) NOT NULL,
MOVIE_GENRE VARCHAR(100),
PRICE_CODE VARCHAR(1),
FOREIGN KEY (PRICE_CODE) REFERENCES PRICE(PRICE_CODE)
);

CREATE TABLE VIDEO (
VID_NUM INT NOT NULL PRIMARY KEY,
VID_INDATE DATE NOT NULL,
MOVIE_NUM INT NOT NULL,
FOREIGN KEY (MOVIE_NUM) REFERENCES MOVIE(MOVIE_NUM)
);

CREATE TABLE DETAILRENTAL (
RENT_NUM INT PRIMARY KEY NOT NULL,
VID_NUM INT PRIMARY KEY NOT NULL,
DETAIL_FEE DECIMAL(2,2),
DETAIL_DUEDATE DATE,
DETAIL_RETURNDATE DATE,
DETAIL_DAILYLATEFEE DECIMAL(2,2),
FOREIGN KEY (RENT_NUM) REFERENCES RENTAL(RENT_NUM),
FOREIGN KEY (VID_NUM) REFERENCES VIDEO(VID_NUM)
);


#2

INSERT INTO MEMBERSHIP VALUES(
(102,'Tami','Dawson','2632 Takli Circle', 'Norene', 'TN', '37136', 11),
(103, 'Curt', 'Knight', '4025 Cornell Court', 'Flatgap', 'KY', '41219', 6),
(104, 'Jamal','Melendez', '788 East 145th Avenue', 'Quebeck', 'TN', '38579', 0),
(105, 'Iva','Mcclain', '6045 Musket Ball Circle', 'Summit', 'KY', '42783', 15)
);


#DROP DATABASE 1907002160_Lokaverkefni;

DROP DATABASE 1907002160_lokaverkefni;